spring:
  rabbitmq:
    host: 192.168.206.8
    port: 15672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin
  mvc:
    view:
      suffix: .jsp
      prefix: /
  redis:
    port: 6379
    password:
    host: 192.168.206.8
    lettuce:
      pool:
        max-idle: 6
        max-active: 10
        min-idle: 2
        max-wait: 1000
      shutdown-timeout: 100
    jedis:
      pool:
        max-idle: 6
        max-active: 10
        min-idle: 2
    timeout: 2000
server:
  port: 8080
