spring:
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin
